### ISSUE TITLE
When new form is added to new customized step on checkout page, install schema.php doesn't work.

### ISSUE THREAD

**Issue by meezin** [sbodak/magento2-checkout-custom-form#10]
https://github.com/meezin/Meezin_CustomerPickup

Hello, 

I created new module referring to your module. 
The thing is that your module added a form to existing step on checkout page. Otherwise, I added a form to a step, created by me, on checkout page.

I tried to save data from new from to `sales_order` and `quote`table as you mentioned on your module. But at my module, neither the data nor the new field couldn't be saved on those tables. 

Can you check this case? 

Thanks a lot.

**Comment by sbodak** [comment]
@meezin You may check your `var/log` directory first and discover what happens.
If you open browser console and check XHR requests/response of `/V1/carts/mine/set-order-custom-fields` or `/V1/guest-carts/:cartId/set-order-custom-field` you can simply check if your modification produced any errors.

Also, I recommend you to use xDebug to check `https://github.com/meezin/Meezin_CustomerPickup/blob/master/Meezin/CustomerPickup/Model/CustomFieldsRepository.php#L76` method to discover what is wrong.


As it's not issue related to my module I will close this.
