### ISSUE TITLE
How to get values for custom fields when order is created from admin panel

### ISSUE THREAD

**Issue by VivekShingala** [sbodak/magento2-checkout-custom-form#13]
Hi

**What is the solution to save custom field details when an order is created using admin panel?** 

Custom values are saved properly when the order is placed through the checkout process in the frontend.

**Comment by sbodak** [comment]
@VivekShingala You can start from extending xml layout for new order creation action in
`module-sales/view/adminhtml/layout/sales_order_create_index.xml`

You need to add a custom form manually and also new template.
Take a look on `module-sales/view/adminhtml/templates/order/create` directory and try to create a new template for a custom form and assign it correctly to the layout.

You also need to create a JS mixin for `module-sales/view/adminhtml/web/order/create/scripts.js` to handle new data.
