### ISSUE TITLE
Form Fields showing above checkout Fields like first name and last name

### ISSUE THREAD

**Issue by myselfgaurav** [sbodak/magento2-checkout-custom-form#14]
I have installed module , but other information form fields shows above customer form fileds like first name , last name and so on.

How can i show this below customer fields

**Comment by sbodak** [comment]
You can check available default placements in:
`/vendor/magento/module-checkout/view/frontend/layout/checkout_index_index.xml`

You can see there that `before-form` is name of item.
```
<item name="shippingAddress" xsi:type="array">
	...
   
	<item name="children" xsi:type="array">
		<item name="customer-email" xsi:type="array">
			...
		</item>
		<item name="before-form" xsi:type="array">
		   ...
		</item>
		<item name="before-fields" xsi:type="array">
		   ...
		</item>
		<item name="address-list" xsi:type="array">
			...
		</item>
		<item name="address-list-additional-addresses" xsi:type="array">
		  ...
		</item>
		<item name="before-shipping-method-form" xsi:type="array">
		  ...
		</item>
		<item name="shipping-address-fieldset" xsi:type="array">
			...
		</item>
	</item>
</item>
```
You can change a place of custom form using a correct node name.

**Comment by myselfgaurav** [comment]
i tried but unable to do can you help with it : https://magento.stackexchange.com/questions/257464/magento-2-add-custom-fields-to-checkout-form-below-shipping-address-form
