### ISSUE TITLE
New fields data not saving in Quote table

### ISSUE THREAD

**Issue by pravinagham** [sbodak/magento2-checkout-custom-form#15]
I have installed module via composer and its working well. But I have changed fields (some are removed and some are newly added) as per my requirements and as per instruction given. 

Now fields data is not saving in quote table. I have notices that new fields are not crated in table after setup:upgrade. tried with uninstall and install several times

My question is how this new field are generated in quote and sales table?
Why fields data are not saved in table columns.

Please help me,

**Comment by sbodak** [comment]
@pravinagham Please take a look for my answer in this ticket:
https://github.com/sbodak/magento2-checkout-custom-form/issues/1#issuecomment-371646962

You can find there a specific answer to your question and information how to modify/change/add new fields and how to manage them.

**Comment by pravinagham** [comment]
@sbodak I have followed all instruction. New fields are showing on checkout page but new field are not created in quote table. I have installed it via composer. Do I need to upgrade version?

**Comment by sbodak** [comment]
@pravinagham Yes, you must upgrade the module version (module.xml) and run command `setup:upgrade`

**Comment by pravinagham** [comment]
@sbodak - I tried all the possible ways. uninstalled & install module several time. now i am stuck. I am using magento2.3 . I have followed all steps mentioned above but new field are not created in quote table.
Let me know if UpgradeSchema  needed for new fields?

**Comment by sbodak** [comment]
Yes, you need to install new fields, I put some information about this here:
https://github.com/sbodak/magento2-checkout-custom-form#modify-form-fields

It's a quite common task so you will figure out how to install it using UpgradeSchema file.
