### ISSUE TITLE
Possible to push this to the order email?

### ISSUE THREAD

**Issue by punch-creative** [sbodak/magento2-checkout-custom-form#16]
Hi,

Fantastic module, really helped me out with this one.

Would it be possible to add the fields to the new order email at all please?

We are getting these in the backend now and ive edited this to just show a different label for what we require but need to be able to show the custom this field also.

Thanks
Paul

**Comment by sbodak** [comment]
@punch-creative yes, you can add it in the same way as all the other values are.
1) changes using transactional emails template
- transactional emails management can be found in **Marketing > Communication > Email Templates** 
- after you create a new template for New Order and New Order - Guest, you need to select a new template in Stores > Configuration > Sales > Sales Emails
2) direct changes in order emails files for New Order and New Order - Guest
- example `<p>{{trans 'New field: %new_field_name' new_field_name=$order.getNewFieldName() }}</p>`
