### ISSUE TITLE
Problem with a custom Theme

### ISSUE THREAD

**Issue by MatteoLidoni** [sbodak/magento2-checkout-custom-form#20]
Hello ! Thanks your module is fantastic, but I have a problem if I use it on the original magento theme it works! But if I install it in a paid theme bought from templatemonster it gives me this problem.

You can see that the checkboxes disappear.

![Screenshot (64)](https://user-images.githubusercontent.com/48811163/54791450-360ac380-4c3a-11e9-9d22-92c73d5e3880.png)
![Screenshot (65)](https://user-images.githubusercontent.com/48811163/54791451-360ac380-4c3a-11e9-8696-5c1369674c66.png)

**Comment by sbodak** [comment]
@MatteoLidoni You must compare
https://github.com/sbodak/magento2-checkout-custom-form/blob/master/view/frontend/web/template/shipping.html
with `shipping.html` file from the custom theme.

**This is probably just a styling issue.**

**Keep in mind that the main modification of this file in my module is between line 31-41:**
https://github.com/sbodak/magento2-checkout-custom-form/blob/master/view/frontend/web/template/shipping.html#L31-L41

**Comment by MatteoLidoni** [comment]
Thanks for your reply!!

This is my shipping.html file : https://codeshare.io/aV03o4 or https://ghostbin.com/paste/ysr5g


But I can't find the problem.
Can you help me?

**Comment by MatteoLidoni** [comment]
Solved.

I added my theme style code in shipping.html at the bottom of the page.
Thanks for your help!
