### ISSUE TITLE
Remove form on the payments page

### ISSUE THREAD

**Issue by MatteoLidoni** [sbodak/magento2-checkout-custom-form#21]
Hello.
Thanks for your previous help, you are very kind.

![image](https://user-images.githubusercontent.com/48811163/54982002-02b59500-4faa-11e9-9033-39766e17d413.png)

Is possible remove form only on the payments page?
Thanks!

**Comment by sbodak** [comment]
@MatteoLidoni hi, are you saying that you are able o see the custom form on both steps, shipping, and payment?

**Comment by MatteoLidoni** [comment]
@sbodak 
I would like to hide the form only on the payment page!
Then display the form on the "Shipping" page and remove it on the "Payment" page

I hope I was clear.

**Comment by sbodak** [comment]
@MatteoLidoni It's probably also a part of your custom theme customization.

My module by default only shows the customs form on the shipping step.

This is a part where the custom form is defined on the `checkout_index_index.xml`
https://github.com/sbodak/magento2-checkout-custom-form/blob/master/view/frontend/layout/checkout_index_index.xml#L16

Just make sure that similar part of code is not present on `payment-step` node.

Also, double check block code from https://github.com/sbodak/magento2-checkout-custom-form/blob/master/view/frontend/web/template/shipping.html#L32

Here is a template for custom form to be shown only on shipping step.

**Comment by MatteoLidoni** [comment]
I installed extension in clean magento 2.2.5 with original theme.
It give me the same problem..

![image](https://user-images.githubusercontent.com/48811163/55036104-ec472200-5019-11e9-988c-0c4c8d8edb08.png)

How it possible?

**Comment by sbodak** [comment]
@MatteoLidoni The latest version (`1.2.*`) has been tested on `M 2.3.`

Not sure what behavior is in`2.2.5`. You can test a tag of `1.1.*`

I can see that you already customize a custom form. 
Probably, you copy-paste something to the wrong place.

Read my comment above and double check.

**Comment by sbodak** [comment]
@MatteoLidoni I found the bug. Fix in progress.

**Comment by sbodak** [comment]
@MatteoLidoni I've fixed this issue. You can check it now.

**Comment by MatteoLidoni** [comment]
@sbodak Thank's for your reply.
Now it works well.
Have a nice day!
