### ISSUE TITLE
The order_custom_fields section would not show up at Backend order view page.

### ISSUE THREAD

**Issue by liuandyu** [sbodak/magento2-checkout-custom-form#22]
Thank you for publishing the extension. There is an issue. Actually, the Address Information section is totally gone for order view page. Other parts are working charmingly.

**Comment by sbodak** [comment]
@liuandyu What Magento version are you using?

**Comment by liuandyu** [comment]
It's CE 2.3.0. I read your codes and I don't understand the logic to show up the custom fields. You directly put the generic Magento Block into 'body', instead of a container.

**Comment by sbodak** [comment]
@liuandyu I've checked all places with custom form and/or details:
1) frontend (guest) - checkout -> shipping step
2) frontend (logged in) - checkout -> shipping step
3) frontend - custom account -> order history -> order details
4) admin - sales -> orders -> order details

All the places look as expected.

1) Here you can find where the Custom form UI component is placed into layout update definition on `checkout_index_index`:
https://github.com/sbodak/magento2-checkout-custom-form/blob/master/view/frontend/layout/checkout_index_index.xml#L16
- custom form component is defined *inside `checkout.root` block* on `<item name="shippingAddress" xsi:type="array">` node.


2) Here is a part where the Custom form UI is defined in template to be rendered.
https://github.com/sbodak/magento2-checkout-custom-form/blob/master/view/frontend/web/template/shipping.html#L32

3) Here is a template for Custom form and definition for fields UI components to be rendered inside
https://github.com/sbodak/magento2-checkout-custom-form/blob/master/view/frontend/web/template/checkout/custom-checkout-form.html#L1
