### ISSUE TITLE
How to add form like this in my custom checkout step and the data is not getting stored in database how to save the data

### ISSUE THREAD

**Issue by thehasan** [sbodak/magento2-checkout-custom-form#26]
How to add form like this in my custom checkout step and the data is not getting stored in database how to save the data.
I have added a checkout step but i am not able to add a form in that step.
I have installed this module and its showing in shipping address field but not getting save.
how can i stored the data and show in  my custom checkout step.
Please Help
Thanks in Advance :)

**Comment by sbodak** [comment]
@thehasan please read carefully the module README.md
https://github.com/sbodak/magento2-checkout-custom-form#modify-form-fields
