### ISSUE TITLE
These new fields are not showing in Customer Order confirmation email.

### ISSUE THREAD

**Issue by sanaullahAhmad** [sbodak/magento2-checkout-custom-form#27]
I have added a question about it in stackoverflow.com here 
https://magento.stackexchange.com/questions/305608/magento-2-show-custom-fields-in-checkout-form-information-in-order-email
i want these fields in customer order confirmation email.

**Comment by webusat** [comment]
@sanaullahAhmad Did you get this to work?

**Comment by sanaullahAhmad** [comment]
Yes i figured it out now @webusat

**Comment by webusat** [comment]
@sanaullahAhmad Awesome, can you share the solution?

**Comment by sanaullahAhmad** [comment]
[Badi.zip](https://github.com/sbodak/magento2-checkout-custom-form/files/4393649/Badi.zip)
Here is a plugin Which is using Magento2 Events and Observer for sending these custom fields to email template.
@webusat

**Comment by webusat** [comment]
@sanaullahAhmad Thanks, I'll check it out!

**Comment by sbodak** [comment]
That's great that you figured out the solution. Regards!
