### ISSUE TITLE
Magento 2.1.7 When enable the module, Checkout crash

### ISSUE THREAD

**Issue by ChristoforosKotsios** [sbodak/magento2-checkout-custom-form#3]
Hello.

I have an e-commerce site in Greece and I need some extra fields in the checkout process. I find your module and I follow its instruction in order to install it. After installation, I had in my mind to modify field labels. 

The problem is that I never got there. After installation, and with the module enabled I try to make a try order to see that module works correctly. 

Unfortunately, I find that in the first step of checkout the module crash and I have not access in the fields. 

I provide to you an photo in order to see your problem by your self. 

Any idea in order to solve it? 
![checkout](https://user-images.githubusercontent.com/35273070/39354885-5acd7218-4a14-11e8-9fd9-8169f784feea.png)

**Comment by sbodak** [comment]
Do you have any specific JS errors?
