### ISSUE TITLE
Magento 2.2.4 When i am installing this extension my checkout page is not working.

### ISSUE THREAD

**Issue by manojm993** [sbodak/magento2-checkout-custom-form#5]
I am trying to resolve this issue but as i check logs files they are not give me any error. only show me js error on console "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data". Please help me 
![issue](https://user-images.githubusercontent.com/37321462/40531301-9a5b2108-6019-11e8-974f-f3beb3284d78.png)

**Comment by sbodak** [comment]
I will check how it works in the latest version and let you know.

**Comment by sbodak** [comment]
I've checked the latest version and it works as expected. It looks like some additional customization issue.
