### ISSUE TITLE
I don't see custom checkout form fields on the page.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [sbodak/magento2-checkout-custom-form#6]
I have been trying to build my own extension to add custom fields to checkout.
Followed a few guides/tutorials but nothing renders as a field in the page.

However I do see their values when viewing the source of the checkout page in this section.

```html
<!-- ko template: getTemplate() --><!-- /ko -->
--
 <script type="text/x-magento-init">
 {
 "#checkout": {
```

I have your extension installed & enabled now.

Note: I do see the new content in the Admin back end.

Any ideas?
Could it be the custom theme on the site?

I do not see any client side errors.

**Comment by sbodak** [comment]
It's independent custom template to render new fields, so rather not.
Do you see any JS errors? Do you have installed some additional extensions for checkout?

Try also static content deploy and after clear cache.

**Comment by sbodak** [comment]
Good to know. Thanks.
