### ISSUE TITLE
Php 7.1 not supported in composer.json

### ISSUE THREAD

**Issue by wesleywmd** [sbodak/magento2-checkout-custom-form#7]
Trying to install module in magento 2.2.5 and php 7.1.22. I receive this error 
`sbodak/magento2-checkout-custom-form 1.1.2 requires php ~7.0.0 -> your PHP version (7.1.22) does not satisfy that requirement.` 

Stating `~7.0.0` is the same as `>=7.0.0 < 7.1.0` which does not include 7.1.22

The READ.md states this modules support php 7.0 and higher which contradicts the composer.json as stated above.

If the module supports php 7.1 and 7.2 then the composer.json should be revised to `~7.0` which is the same as `>=7.1 < 8.0` which covers all versions of php7.

If module only supports 7.0 and 7.1 and nothing higher, then composer.json should be revised to `~7.0.0|~7.1.0`.

If module doesn't support anything higher then 7.0, then the READ.md should be updated to state "only works with 7.0, higher versions not supported".

This blocks composer installing module on anything higher then php 7.0.

**Comment by sbodak** [comment]
@wesleywmd Just updated composer, please take it now.

**Comment by wesleywmd** [comment]
It still won't work for me. You set the constraint to ~7.1.3 and we are on 7.1.22 which means the our version still will not pass the check.

**Comment by sbodak** [comment]
Are you sure?
~7.1.3 doesn't mean that  >=7.1.3 <7.2.0 ?

**Comment by wesleywmd** [comment]
oh! your right. I am think "2" is before "3" instead of seeing it as a "22" and being after "3".

I will test in my project and get back to you.

**Comment by sbodak** [comment]
@wesleywmd I'll close this issue. If you will have any other problem let me know.
