### ISSUE TITLE
While installing the extention getting this warning Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.

### ISSUE THREAD

**Issue by VivekShingala** [sbodak/magento2-checkout-custom-form#8]
Hi @sbodak 

Thank you for this extension. However, while installing it recently, it gave me this warning.

Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.

**Comment by sbodak** [comment]
@VivekShingala The warning you mentioned above is not related to this repository. Read the warning and follow steps you received.

**Comment by VivekShingala** [comment]
Hi @sbodak 

My bad! I actually realised it after logging this bug and forgot to close it before your reply.

Thank you for your reply.
